accepted = [
    "Apache-2.0",
    "MPL-2.0",
    "CC0-1.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "MIT",
    "OpenSSL",
    "LGPL-3.0"
]

no-clearly-defined = true
