[target.x86_64-unknown-linux-gnu]
# A newer gcc version is needed to compile aws-lc-sys
pre-build = ["apt update", "apt install -y gcc-10 clang", "curl -fsSL https://github.com/rui314/mold/releases/download/v2.34.0/mold-2.34.0-x86_64-linux.tar.gz | tar -xz --strip-components=1 -C /usr/local"]

[build.env]
passthrough = [
  "CC=gcc-10"
]
