extend = "common.toml"

[config]
load_script = "wget -nc https://raw.githubusercontent.com/cpg314/cargo-make-template/v0.1.3/common.toml"

[env]
VITE_SQLSONNET_VERSION = "${CARGO_MAKE_PROJECT_VERSION}"

[tasks.pestfmt]
command = "pestfmt"
args = ["."]

[tasks.help]
script = '''
#!/usr/bin/env bash
set -euo pipefail
COMMAND="cargo run -q -r --bin sqlsonnet --"
eval $COMMAND --help
'''

[tasks.release]
dependencies = ["update-pages-branch"]

[tasks.cross]
dependencies = ["playground-proxy"]

[tasks.tests]
dependencies = ["docker-compose"]
command = "cargo"
args = ["nextest", "run", "r", "--workspace"]

[tasks.docs]
command = "cargo"
args = ["doc", "--workspace", "--all-features"]

[tasks.checkalot]
dependencies = ["playground-proxy", "docker-compose"]
command = "checkalot"

[tasks.docker-compose]
command = "docker"
args = ["compose", "up", "-d"]

################
# WASM bindings
################
[tasks.wasm]
command = "wasm-pack"
args = ["build", "--target", "web", "bindings/wasm/"]
condition = { files_modified = { input = ["./sqlsonnet/**/*", "./bindings/wasm/src/**/*"], output = ["./bindings/wasm/pkg/*"] } }

[tasks.wasm-dev]
command = "wasm-pack"
args = ["build", "--target", "web", "--dev", "bindings/wasm/"]

[tasks.playground-install]
condition = { files_modified = { input = ["package.json", "package-lock.json"], output = ["node_modules/**/*"] } }
cwd = "playground"
command = "npm"
args = ["install"]

################
# Playground for the clickhouse proxy
################
[tasks.playground-proxy]
dependencies = ["wasm", "playground-install"]
condition = { files_modified = { input = ["src/*", "*.json", "*.ts", "../bindings/wasm/pkg/*"], output = ["dist-proxy/*"] } }
env = { "VITE_PROXY" = "1" }
cwd = "playground"
script = '''
#!/usr/bin/env bash
set -euo pipefail

npm run build --emptyOutDir
rm dist-proxy/assets/*.wasm
tree dist-proxy
'''
[tasks.playground-proxy-run]
dependencies = ["wasm-dev", "playground-install"]
env = { "VITE_PROXY" = "1", "VITE_WEBSOCKET" = "ws://localhost:1234/play/ws" }
cwd = "playground"
command = "npm"
args = ["run", "dev"]

################
# Standalone playground
################
[tasks.playground-wasm]
env = { "VITE_PROXY" = "0" }
script = '''
#!/usr/bin/env bash
set -euo pipefail

pushd playground
npm run build --emptyOutDir
popd

touch docs/.nojekyll
tree -a docs
'''

[tasks.update-pages-branch]
dependencies = ["playground-wasm"]
script = '''
#!/usr/bin/env bash
set -euo pipefail

git branch -f pages main
git checkout pages
git add docs
git commit -m Playground
git push -f origin pages
git checkout main
git --no-pager log pages -n1
'''

[tasks.playground-wasm-run]
extend = "playground-proxy-run"
env = { "VITE_PROXY" = "0" }

