extend = "common.toml"

[config]
load_script = "wget -nc https://raw.githubusercontent.com/cpg314/cargo-make-template/v0.1.1/common.toml"

[tasks.pestfmt]
command = "pestfmt"
args = ["."]

[tasks.help]
script = '''
#!/usr/bin/env bash
COMMAND="cargo run -q -r --bin sqlsonnet --"
eval $COMMAND --help
eval $COMMAND to-sql --help
eval $COMMAND from-sql --help
'''
