[package]
name = "sqlsonnet-macros"
version.workspace = true
license.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
jrsonnet-parser.workspace = true
syn = "2.0.73"
proc-macro2 = "1.0.86"
